modLoader="javafml"
loaderVersion="[32,)" 
logoFile="logo.png" 
[[mods]]
modId="itemdespawncanseler"
version="${file.jarVersion}" 
displayName="Item Despawn Canseler"
displayURL="https://www.curseforge.com/minecraft/mc-mods/itemdespawncanseler" 
authors="MORIMORI0317" 
description="Thank you for downloading!"
